package com.stuiversity.api.auth

object AuthErrors {
    const val REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED"
    const val INVALID_GRANT = "INVALID_GRANT"
    const val WRONG_EMAIL = "WRONG_EMAIL"
    const val USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED"
    const val PASSWORD_MUST_CONTAIN_AT_LEAST_6_CHARACTERS = "PASSWORD_MUST_CONTAIN_AT_LEAST_6_CHARACTERS"
    const val PASSWORD_MUST_CONTAIN_UPPER_AND_LOWER_CASE_CHARACTERS =
        "PASSWORD_MUST_CONTAIN_UPPER_AND_LOWER_CASE_CHARACTERS"
    const val PASSWORD_MUST_CONTAIN_DIGITS = "PASSWORD_MUST_CONTAIN_DIGITS"
}